[build]
  command = "sed -i 's/%%MAPS_API_KEY%%/'$MAPS_API_KEY'/g' index.html"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
